### ISSUE TITLE
NTLM Challenge and Auth messages are not performed throughout the same connection when performed in an https CONNECT

### ISSUE THREAD

**Issue by fsgonz** [javaee/grizzly-ahc#11]
Hello,

When an NTLM auth goes from a HTTP proxy to HTTPS site, I've found that the NTLM dancing performed does not involve the same connection for the Challenge (message type 2) and the Auth (message type 3). That makes the authentication fail in some proxy with NTLM (for example in McAfee, the issue does arise in ISA Server).
I've opened [PR](https://github.com/javaee/grizzly-ahc/pull/10) that may be a fix for this issue.

The following [link](https://community.mcafee.com/message/463105#463105) in the McAfee web gateway community haas a tcdump illustrating the issue.

**Comment by ghost** [comment]
PR applied.  Thanks!
