### ISSUE TITLE
dependencies need to be updated to latest version.

### ISSUE THREAD

**Issue by vinayvishal** [javaee/grizzly-ahc#21]
GroupId|Version|Release Date|Latest Version|Release Date
--|--|--|--|--
org.eclipse.jetty:jetty-websocket	|8.1.1.v20120215| Feb 2012 | 8.2.0.v20160908 |Sep 2016 
org.apache.tomcat:catalina	|6.0.29| July 2010 |6.0.53 | Apr 2017
org.eclipse.jetty:jetty-servlets	|8.1.1.v20120215|Feb 2012 |9.4.8.v20171121 |Nov 2017 
org.eclipse.jetty:jetty-servlet	|8.1.1.v20120215| Feb 2012|9.4.8.v20171121 |Nov 2017 
ch.qos.logback:logback-classic	|1.1.3|Mar 2015 |1.2.3 |Mar 2017  
org.apache.tomcat:coyote	|6.0.29| July 2010|6.0.53 |Apr 2017
org.eclipse.jetty:jetty-security	|8.1.1.v20120215|Feb 2012 | 9.4.8.v20171121|Nov 2017
org.eclipse.jetty:jetty-server	|8.1.1.v20120215|Feb 2012 | 9.4.8.v20171121| Nov 2017

**Comment by anajosep** [comment]
All jetty Issues are upgraded to the latest version 9.4.9. Fix available from version Grizzly AHC 1.15 onwards.
