### ISSUE TITLE
Proxy Basic Auth not working going from HTTP to HTTP

### ISSUE THREAD

**Issue by ghost** [javaee/grizzly-ahc#3]
I've reported the following issue to AHC 1.9.x when using Grizzly and proxies.

> Proxy Basic Auth not working going from HTTP to HTTP (1.9.x)

[https://github.com/AsyncHttpClient/async-http-client/issues/1321#issuecomment-272541801](https://github.com/AsyncHttpClient/async-http-client/issues/1321#issuecomment-272541801)

It is not a Grizzly issue but as we use Grizzly through AHC 1.9.x and seems that AHC 1.9 has reached end-of-life you could have a forked AHC to support it.
The ticket reported also provides a possible solution to the issue.
#### Affected Versions
[2.3.26]

**Comment by ghost** [comment]
Copied from:  https://github.com/javaee/grizzly/issues/1883

**Comment by ghost** [comment]
@gsfernandes In case you missed the comment on your branch that resolves this issue, if you could create a PR without whitespace or optimize import changes I'm more than happy to look into merging.

**Comment by gsfernandes** [comment]
Sure, I will do it and let you know.

**Comment by gsfernandes** [comment]
Hi @rlubke, I just sent the PR. Don't hesitate and let me know if there are any questions. Thanks!

**Comment by ghost** [comment]
Thanks for the contribution!
