### ISSUE TITLE
Feature.get() blocks forever in some scenarios.

### ISSUE THREAD

**Issue by facundovs** [javaee/grizzly-ahc#9]
If I have a AsyncHttpClient that executes a request with an AsyncHandler, and inside the AsyncHandler executes other request with the same client, when I called future.get(), this blocks forever.
If I used two differents clients, I can get the expected behavior.
I have created [this test case](https://github.com/facundovs/grizzly-ahc/commit/cda28baf91b9305769b6badc7ef6ee88c6b4ea89) to reproduce the bug in my fork.

**Comment by facundovs** [comment]
Hi Guys.
Do you have any news regarding to this case?

**Comment by ghost** [comment]
You're making a blocking call within the AsyncCompletionHandler that prevents the runtime from re-enabling OP_READ on the connection allowing the second response to be read.

If you need to execute additional requests from within the handler, I would recommend doing something like:

```java
 final ListenableFuture<Response> future =
                    clientHandler.executeRequest(request, new AsyncCompletionHandlerBase());
            future.addListener(new Runnable() {
                @Override
                public void run() {
                    try {
                        final Response r = future.get();
                        System.out.println(r.toString());
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    } catch (ExecutionException e) {
                        e.printStackTrace();
                    }
                }
            }, Executors.newSingleThreadExecutor());
```

**Comment by ghost** [comment]
Closing this out.  If you still feel that this is a bug, please reopen with reasons as to why and they can be discussed.
